# Generated by Django 5.2.9 on 2026-01-05 15:08

import members.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_expiry_date_alter_member_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='membership_type',
            field=models.CharField(choices=[('1', '1 Month'), ('3', '3 Months'), ('6', '6 Months'), ('12', '12 Months')], default='1', max_length=2),
        ),
        migrations.AlterField(
            model_name='member',
            name='join_date',
            field=models.DateField(default=members.models.today_date),
        ),
    ]
