# Generated by Django 5.2.9 on 2026-01-07 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_membership_type_alter_member_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
